# Generated by Django 4.1.7 on 2023-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='nombre_de_la_materia',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
