# Generated by Django 4.1.7 on 2023-04-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0002_alter_catedra_nombre_de_la_materia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiantes',
            new_name='Estudiante',
        ),
        migrations.RenameModel(
            old_name='profesores',
            new_name='Profesor',
        ),
    ]
