# Generated by Django 4.1.7 on 2023-04-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_post',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesposteadas'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
