# Generated by Django 4.1.7 on 2023-04-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0006_post_descripcion_post_imagen_post_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=99, null=True, unique=True),
        ),
    ]
